const {
  REACT_APP_ENV,
  REACT_APP_DEV_API_URL,
  REACT_APP_PROD_API_URL,
  REACT_APP_PUSHER_KEY
} = process.env

const API_URL = REACT_APP_ENV === 'prod' ? REACT_APP_PROD_API_URL : REACT_APP_DEV_API_URL; 
export {API_URL, REACT_APP_PUSHER_KEY};
